### PR TITLE
Added ingress + customization

### PR DESCRIPTION
**Pull request by ajoyej**

### CODE REVIEW

**Comment by stakater-user** [comment]
@ajoyej [Build 1](https://jenkins.release.stakater.com/job/stakater-charts/job/pgadmin/job/PR-14/1/) has Failed!

**Comment by ahmadiq** [comment]
> @ajoyej [Build 1](https://jenkins.release.stakater.com/job/stakater-charts/job/pgadmin/job/PR-14/1/) has Failed!

@ajoyej FYI:
```
+ cd /home/jenkins/pgadmin/pgadmin
+ helm lint
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "pgadmin/templates/secrets.yaml": template: pgadmin/templates/secrets.yaml:11:61: executing "pgadmin/templates/secrets.yaml" at <b64enc>: wrong number of args for b64enc: want 1 got 0

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Comment by ajoyej** [comment]
Hello,

 

This is very strange….

I have cloned the project back to me and lint is more than happy on my side

 

Regards,

José

 

De : Ahmad Iqbal Ali <notifications@github.com> 
Envoyé : lundi, 15 avril 2019 13:55
À : stakater-charts/pgadmin <pgadmin@noreply.github.com>
Cc : José Joye <jose.joye@bluewin.ch>; Mention <mention@noreply.github.com>
Objet : Re: [stakater-charts/pgadmin] Added ingress + customization (#14)

 

@ajoyej <https://github.com/ajoyej>  Build 1 <https://jenkins.release.stakater.com/job/stakater-charts/job/pgadmin/job/PR-14/1/>  has Failed!

@ajoyej <https://github.com/ajoyej>  FYI:

+ cd /home/jenkins/pgadmin/pgadmin
+ helm lint
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "pgadmin/templates/secrets.yaml": template: pgadmin/templates/secrets.yaml:11:61: executing "pgadmin/templates/secrets.yaml" at <b64enc>: wrong number of args for b64enc: want 1 got 0
 
Error: 1 chart(s) linted, 1 chart(s) failed

**Comment by ajoyej** [comment]
I have added a modification to try to fix the issue

**Comment by stakater-user** [comment]
@ajoyej [Build 2](https://jenkins.release.stakater.com/job/stakater-charts/job/pgadmin/job/PR-14/2/) has Failed!

**Comment by ahmadiq** [comment]
> Hello, This is very strange…. I have cloned the project back to me and lint is more than happy on my side

yes, it seemed ok in my local copy as well. I'm checking further on Jenkins.

**Comment by kahootali** [comment]
@ajoyej You need to update the values.yaml.tmpl file as in pipeline, that file is the one that generates the values.yaml file. Please update that as well with the changes.

**Comment by ahmadiq** [comment]
> @ajoyej [Build 2](https://jenkins.release.stakater.com/job/stakater-charts/job/pgadmin/job/PR-14/2/) has Failed!

@ajoyej 
```
[ERROR] templates/: render error in "pgadmin/templates/pvc.yaml": template: pgadmin/templates/pvc.yaml:1:14: executing "pgadmin/templates/pvc.yaml" at <.Values.pgadmin.pers...>: can't evaluate field enabled in type interface {}
```

**Comment by stakater-user** [comment]
@ajoyej Chart: pgadmin Dry Run successful

**Comment by ajoyej** [comment]
Hello,

I have done the modification

 

José

 

De : Ali Kahoot <notifications@github.com> 
Envoyé : mardi, 16 avril 2019 08:36
À : stakater-charts/pgadmin <pgadmin@noreply.github.com>
Cc : José Joye <jose.joye@bluewin.ch>; Mention <mention@noreply.github.com>
Objet : Re: [stakater-charts/pgadmin] Added ingress + customization (#14)

 

@ajoyej <https://github.com/ajoyej>  You need to update the values.yaml.tmpl file as in pipeline, that file is the one that generates the values.yaml file. Please update that as well with the changes.

**Comment by stakater-user** [comment]
@ajoyej Chart: pgadmin Dry Run successful

**Comment by kahootali** [comment]
@ajoyej merged, thanks for contributing

**Pull request merged**
